# Imagem base com Maven e Java 17
FROM mcr.microsoft.com/devcontainers/java:17

# Instalar Maven (caso não esteja na imagem base)
RUN apt-get update && apt-get install -y maven

# Configura o diretório de trabalho
WORKDIR /workspace
